name: Create Production Builds

on:
  push:
    branches: ["main"]

jobs:
  build_ios:
    type: build
    params:
      platform: ios
      profile: production
  submit_ios:
    type: submit
    needs: [build_ios]
    params:
      platform: ios
      profile: production
      # Use the build from the previous job
      build_id: ${{ needs.build_ios.outputs.build_id }}
